import {
  ArchiveBoxIcon,
  ArrowRightStartOnRectangleIcon,
  ArrowsPointingOutIcon,
  BuildingStorefrontIcon,
  ChatBubbleLeftRightIcon,
  InboxStackIcon,
  ReceiptPercentIcon,
  RectangleGroupIcon,
  RectangleStackIcon,
  SparklesIcon,
  Square3Stack3DIcon,
  TruckIcon,
  UserGroupIcon,
  UserIcon,
  ViewfinderCircleIcon,
  WalletIcon,
  WindowIcon,
} from '@heroicons/react/24/outline';

export enum STATUS {
  ACTIVE = 'active',
  INACTIVE = 'inactive',
}

export const EmailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export enum COUNTRY_CODE {
  VN = 'vi-VN',
  EN = 'en-US',
}

export enum ROLE {
  ADMIN = 'admin',
  MANAGER = 'manager',
  USER = 'user',
}

export enum TOAST_TYPE {
  SUCCESS = 'success',
  ERROR = 'error',
  INFO = 'info',
}

export const SENDBIRD_COLOR_SET = {
  '--sendbird-light-primary-extra-light': '#fff1f2',
  '--sendbird-light-primary-light': '#ffe4e6',
  '--sendbird-light-primary-main': '#e11d48',
  '--sendbird-light-primary-dark': '#be123c',
  '--sendbird-light-primary-extra-dark': '#9f1239',
  '--sendbird-light-primary-100': '#fff1f2',
  '--sendbird-light-primary-200': '#ffe4e6',
  '--sendbird-light-primary-300': '#fda4af',
  '--sendbird-light-primary-400': '#fb7185',
  '--sendbird-light-primary-500': '#e11d48',
};

export const SENDBIRD_STRING_SET = {
  TRYING_TO_CONNECT: 'Đang kết nối...',
  CHANNEL__MESSAGE_LIST__NOTIFICATION__NEW_MESSAGE: 'Tin nhắn mới',
  CHANNEL__MESSAGE_LIST__NOTIFICATION__NEW_MESSAGE_S: 'Tin nhắn mới',
  CHANNEL__MESSAGE_LIST__NOTIFICATION__UNREAD_MESSAGE: 'Tin nhắn chưa đọc',
  CHANNEL__MESSAGE_LIST__NOTIFICATION__UNREAD_MESSAGE_S: 'Tin nhắn chưa đọc',
  CHANNEL_PREVIEW_MOBILE_LEAVE: 'Rời',
  CHANNEL_FROZEN: 'Kênh đã bị đóng băng',
  PLACE_HOLDER__NO_CHANNEL: 'Chọn một cuộc trò chuyện để bắt đầu',
  PLACE_HOLDER__WRONG: 'Đã xảy ra lỗi',
  PLACE_HOLDER__RETRY_TO_CONNECT: 'Thử kết nối lại',
  PLACE_HOLDER__NO_MESSAGES: 'Chưa có tin nhắn',
  TOOLTIP__AND_YOU: 'và bạn',
  TOOLTIP__YOU: 'Bạn',
  TOOLTIP__UNKNOWN_USER: 'Người dùng không xác định',
  UNKNOWN__UNKNOWN_MESSAGE_TYPE: 'Loại tin nhắn không hỗ trợ',
  UNKNOWN__CANNOT_READ_MESSAGE: 'Không thể đọc tin nhắn',
  UNKNOWN__TEMPLATE_ERROR: 'Không thể hiển thị mẫu tin nhắn',
  FORM_VERSION_ERROR: 'Phiên bản biểu mẫu không được hỗ trợ',
  UNKNOWN__CANNOT_READ_TEMPLATE: 'Không thể đọc mẫu tin nhắn',
  MESSAGE_EDITED: 'đã chỉnh sửa',

  MESSAGE_INPUT__PLACE_HOLDER: 'Nhập tin nhắn',
  MESSAGE_INPUT__PLACE_HOLDER__DISABLED: 'Bạn không thể gửi tin nhắn',
  MESSAGE_INPUT__PLACE_HOLDER__SUGGESTED_REPLIES: 'Chọn một câu trả lời',
  MESSAGE_INPUT__PLACE_HOLDER__MESSAGE_FORM: 'Điền biểu mẫu',
  MESSAGE_INPUT__PLACE_HOLDER__FROZEN: 'Kênh này đã bị đóng băng',
  MESSAGE_INPUT__PLACE_HOLDER__MUTED: 'Bạn đã bị tắt tiếng',
  MESSAGE_INPUT__PLACE_HOLDER__MUTED_SHORT: 'Đã bị tắt tiếng',
  MESSAGE_INPUT__QUOTE_REPLY__PLACE_HOLDER: 'Trả lời tin nhắn',
  MESSAGE_INPUT__PLACE_HOLDER__FILE_ATTACHED: 'Thêm nội dung tin nhắn',
  MESSAGE_INPUT__PENDING_FILE__TYPE_UNKNOWN: 'Tệp không xác định',
  MESSAGE_INPUT__PENDING_FILE__REMOVE: 'Xóa',

  BUTTON__SUBMIT: 'Gửi',
  BUTTON__CANCEL: 'Hủy',
  BUTTON__DELETE: 'Xóa',
  BUTTON__SAVE: 'Lưu',
  BUTTON__CREATE: 'Tạo',
  BUTTON__INVITE: 'Mời',
  BUTTON__OK: 'OK',
  BADGE__OVER: '+%d',
  NO_TITLE: 'Không có tiêu đề',
  NO_NAME: 'Không có tên',
  NO_MEMBERS: 'Không có thành viên',
  LABEL__OPERATOR: 'Điều phối viên',

  MESSAGE_MENU__COPY: 'Sao chép',
  MESSAGE_MENU__REPLY: 'Trả lời',
  MESSAGE_MENU__THREAD: 'Chuỗi trả lời',
  MESSAGE_MENU__OPEN_IN_CHANNEL: 'Mở trong kênh',
  MESSAGE_MENU__EDIT: 'Chỉnh sửa',
  MESSAGE_MENU__RESEND: 'Gửi lại',
  MESSAGE_MENU__DELETE: 'Xóa',
  MESSAGE_MENU__SAVE: 'Lưu',
  MESSAGE_MENU__MARK_AS_UNREAD: 'Đánh dấu chưa đọc',
  CONTEXT_MENU_DROPDOWN__COPY: 'Sao chép',
  CONTEXT_MENU_DROPDOWN__EDIT: 'Chỉnh sửa',
  CONTEXT_MENU_DROPDOWN__RESEND: 'Gửi lại',
  CONTEXT_MENU_DROPDOWN__DELETE: 'Xóa',
  CONTEXT_MENU_DROPDOWN__SAVE: 'Lưu',

  SEARCH: 'Tìm kiếm',
  SEARCH_IN_CHANNEL: 'Tìm trong cuộc trò chuyện',
  SEARCH_IN: 'Tìm trong',
  SEARCHING: 'Đang tìm kiếm...',
  NO_SEARCHED_MESSAGE: 'Không tìm thấy tin nhắn',

  MODAL__DELETE_MESSAGE__TITLE: 'Xóa tin nhắn này?',
  MODAL__CHANNEL_INFORMATION__TITLE: 'Thông tin cuộc trò chuyện',
  MODAL__CHANNEL_INFORMATION__CHANNEL_IMAGE: 'Ảnh cuộc trò chuyện',
  MODAL__CHANNEL_INFORMATION__UPLOAD: 'Tải ảnh lên',
  MODAL__CHANNEL_INFORMATION__CHANNEL_NAME: 'Tên cuộc trò chuyện',
  MODAL__CHANNEL_INFORMATION__INPUT__PLACE_HOLDER: 'Nhập tên cuộc trò chuyện',
  MODAL__INVITE_MEMBER__TITLE: 'Mời thành viên',
  MODAL__INVITE_MEMBER__SELECTED: 'Đã chọn',
  MODAL__CHOOSE_CHANNEL_TYPE__TITLE: 'Chọn loại cuộc trò chuyện',
  MODAL__CHOOSE_CHANNEL_TYPE__GROUP: 'Nhóm',
  MODAL__CHOOSE_CHANNEL_TYPE__SUPER_GROUP: 'Siêu nhóm',
  MODAL__CHOOSE_CHANNEL_TYPE__BROADCAST: 'Phát sóng',
  MODAL__CREATE_CHANNEL__TITLE: 'Tạo cuộc trò chuyện',
  MODAL__CREATE_CHANNEL__GROUP: 'Nhóm',
  MODAL__CREATE_CHANNEL__SUPER: 'Siêu nhóm',
  MODAL__CREATE_CHANNEL__BROADCAST: 'Phát sóng',
  MODAL__CREATE_CHANNEL__SELECTED: 'Đã chọn',
  MODAL__LEAVE_CHANNEL__TITLE: 'Rời cuộc trò chuyện?',
  MODAL__LEAVE_CHANNEL__FOOTER:
    'Bạn sẽ không nhận tin nhắn từ cuộc trò chuyện này nữa.',
  MODAL__VOICE_MESSAGE_INPUT_DISABLED__TITLE_MUTED:
    'Bạn không thể gửi tin nhắn thoại vì đã bị tắt tiếng.',
  MODAL__VOICE_MESSAGE_INPUT_DISABLED__TITLE_FROZEN:
    'Bạn không thể gửi tin nhắn thoại vì kênh đã bị đóng băng.',

  CHANNEL_SETTING__HEADER__TITLE: 'Thông tin cuộc trò chuyện',
  CHANNEL_SETTING__PROFILE__EDIT: 'Chỉnh sửa thông tin',
  CHANNEL_SETTING__MEMBERS__TITLE: 'Thành viên',
  CHANNEL_SETTING__MEMBERS__SEE_ALL_MEMBERS: 'Xem tất cả thành viên',
  CHANNEL_SETTING__MEMBERS__INVITE_MEMBER: 'Mời thành viên',
  CHANNEL_SETTING__MEMBERS__YOU: 'Bạn',
  CHANNEL_SETTING__MEMBERS__SELECT_TITLE: 'Chọn thành viên',
  CHANNEL_SETTING__MEMBERS__OPERATOR: 'Điều phối viên',
  CHANNEL_SETTING__LEAVE_CHANNEL__TITLE: 'Rời cuộc trò chuyện',
  CHANNEL_SETTING__OPERATORS__TITLE: 'Điều phối viên',
  CHANNEL_SETTING__OPERATORS__TITLE_ALL: 'Tất cả điều phối viên',
  CHANNEL_SETTING__OPERATORS__TITLE_ADD: 'Thêm điều phối viên',
  CHANNEL_SETTING__OPERATORS__ADD_BUTTON: 'Thêm',
  CHANNEL_SETTING__MUTED_MEMBERS__TITLE: 'Thành viên bị tắt tiếng',
  CHANNEL_SETTING__MUTED_MEMBERS__TITLE_ALL: 'Tất cả thành viên bị tắt tiếng',
  CHANNEL_SETTING__NO_UNMUTED: 'Không có thành viên bị tắt tiếng',
  CHANNEL_SETTING__BANNED_MEMBERS__TITLE: 'Thành viên bị chặn',
  CHANNEL_SETTING__FREEZE_CHANNEL: 'Đóng băng kênh',
  CHANNEL_SETTING__MODERATION__REGISTER_AS_OPERATOR: 'Đặt làm điều phối viên',
  CHANNEL_SETTING__MODERATION__UNREGISTER_OPERATOR: 'Gỡ quyền điều phối viên',
  CHANNEL_SETTING__MODERATION__MUTE: 'Tắt tiếng',
  CHANNEL_SETTING__MODERATION__UNMUTE: 'Bỏ tắt tiếng',
  CHANNEL_SETTING__MODERATION__BAN: 'Chặn',
  CHANNEL_SETTING__MODERATION__UNBAN: 'Bỏ chặn',
  CHANNEL_SETTING__MODERATION__EMPTY_BAN: 'Không có thành viên bị chặn',
  CHANNEL_SETTING__MODERATION__ALL_BAN: 'Tất cả thành viên bị chặn',

  USER_PROFILE__MESSAGE: 'Nhắn tin',
  USER_PROFILE__USER_ID: 'ID người dùng',
  EDIT_PROFILE__TITLE: 'Chỉnh sửa hồ sơ',
  EDIT_PROFILE__IMAGE_LABEL: 'Ảnh đại diện',
  EDIT_PROFILE__IMAGE_UPLOAD: 'Tải ảnh lên',
  EDIT_PROFILE__NICKNAME_LABEL: 'Tên hiển thị',
  EDIT_PROFILE__NICKNAME_PLACEHOLDER: 'Nhập tên hiển thị',
  EDIT_PROFILE__USERID_LABEL: 'ID người dùng',
  EDIT_PROFILE__THEME_LABEL: 'Giao diện',

  TYPING_INDICATOR__IS_TYPING: 'đang nhập',
  TYPING_INDICATOR__AND: 'và',
  TYPING_INDICATOR__ARE_TYPING: 'đang nhập',
  TYPING_INDICATOR__MULTIPLE_TYPING: 'Nhiều người đang nhập',

  QUOTE_MESSAGE_INPUT__REPLY_TO: 'Trả lời',
  QUOTE_MESSAGE_INPUT__FILE_TYPE_IMAGE: 'Ảnh',
  QUOTE_MESSAGE_INPUT__FILE_TYPE_GIF: 'GIF',
  QUOTE_MESSAGE_INPUT__FILE_TYPE__VIDEO: 'Video',
  QUOTED_MESSAGE__REPLIED_TO: 'đã trả lời',
  QUOTED_MESSAGE__CURRENT_USER: 'bạn',
  QUOTED_MESSAGE__UNAVAILABLE: 'Tin nhắn không khả dụng',
  THREAD__HEADER_TITLE: 'Chuỗi trả lời',
  CHANNEL__THREAD_REPLY: '%d trả lời',
  CHANNEL__THREAD_REPLIES: '%d trả lời',
  CHANNEL__THREAD_OVER_MAX: '99+ trả lời',
  THREAD__THREAD_REPLY: '%d trả lời',
  THREAD__THREAD_REPLIES: '%d trả lời',
  THREAD__INPUT__REPLY_TO_THREAD: 'Trả lời vào chuỗi',
  THREAD__INPUT__REPLY_IN_THREAD: 'Trả lời trong chuỗi',

  MENTION_NAME__NO_NAME: 'Không có tên',
  MENTION_COUNT__OVER_LIMIT: '+%d',
  UI__FILE_VIEWER__UNSUPPORT: 'Không hỗ trợ xem trước tệp này',
  VOICE_RECORDING_PERMISSION_DENIED:
    'Trình duyệt chưa được cấp quyền dùng micro.',
  VOICE_MESSAGE: 'Tin nhắn thoại',
  CHANNEL_PREVIEW_LAST_MESSAGE_FILE_TYPE_GIF: 'GIF',
  CHANNEL_PREVIEW_LAST_MESSAGE_FILE_TYPE_PHOTO: 'Ảnh',
  CHANNEL_PREVIEW_LAST_MESSAGE_FILE_TYPE_VIDEO: 'Video',
  CHANNEL_PREVIEW_LAST_MESSAGE_FILE_TYPE_AUDIO: 'Âm thanh',
  CHANNEL_PREVIEW_LAST_MESSAGE_FILE_TYPE_VOICE_MESSAGE: 'Tin nhắn thoại',
  CHANNEL_PREVIEW_LAST_MESSAGE_FILE_TYPE_GENERAL: 'Tệp',
  CHANNEL_PREVIEW_LAST_MESSAGE_TEMPLATE_MESSAGE: 'Tin nhắn biểu mẫu',
  FILE_UPLOAD_NOTIFICATION__COUNT_LIMIT:
    'Bạn chỉ có thể tải lên tối đa %d tệp.',
  FILE_UPLOAD_NOTIFICATION__SIZE_LIMIT: 'Tệp vượt quá dung lượng cho phép.',
  FILE_UPLOAD_NOTIFICATION__UNSUPPORTED_FILE_TYPE:
    'Định dạng tệp không được hỗ trợ.',
  FEEDBACK_LIKE: 'Hữu ích',
  FEEDBACK_DISLIKE: 'Không hữu ích',
  EDIT_COMMENT: 'Chỉnh sửa bình luận',
  REMOVE_FEEDBACK: 'Xóa phản hồi',
  FEEDBACK_MODAL_TITLE: 'Gửi phản hồi',
  FEEDBACK_CONTENT_PLACEHOLDER: 'Nhập phản hồi',
  BUTTON__REMOVE_FEEDBACK: 'Xóa phản hồi',
  FEEDBACK_FAILED_SUBMIT: 'Không thể gửi phản hồi',
  FEEDBACK_FAILED_SAVE: 'Không thể lưu phản hồi',
  FEEDBACK_FAILED_DELETE: 'Không thể xóa phản hồi',
  FORM_ITEM_REQUIRED: 'Thông tin bắt buộc',
  FORM_ITEM_INVALID: 'Thông tin không hợp lệ',
  FORM_ITEM_OPTIONAL_EMPTY: 'Không có thông tin',
};

export const ADMIN_ROUTES = [
  {
    href: '/admin/dashboard',
    label: 'Dashboard',
    icon: WindowIcon,
  },
  {
    href: '/admin/product-management',
    label: 'Sản Phẩm',
    icon: InboxStackIcon,
  },
  {
    href: '/admin/product-item-management',
    label: 'Mặt Hàng Sản Phẩm',
    icon: Square3Stack3DIcon,
  },
  {
    href: '/admin/discount-management',
    label: 'Khuyến Mãi',
    icon: ReceiptPercentIcon,
  },
  {
    href: '/admin/size-management',
    label: 'Kích Thước',
    icon: ViewfinderCircleIcon,
  },
  {
    href: '/admin/size-type-management',
    label: 'Loại Kích Thước',
    icon: ArrowsPointingOutIcon,
  },
  { href: '/admin/user-management', label: 'Người Dùng', icon: UserIcon },
  { href: '/admin/color-management', label: 'Màu', icon: SparklesIcon },
  {
    href: '/admin/brand-management',
    label: 'Thương Hiệu',
    icon: RectangleGroupIcon,
  },
  {
    href: '/admin/category-management',
    label: 'Danh Mục',
    icon: RectangleStackIcon,
  },
  { href: '/admin/order-management', label: 'Đơn Hàng', icon: ArchiveBoxIcon },
  {
    href: '/admin/payment-management',
    label: 'Thanh Toán',
    icon: WalletIcon,
  },
  {
    href: '/admin/supplier-management',
    label: 'Nhà Cung Cấp',
    icon: UserGroupIcon,
  },
  { href: '/admin/import-management', label: 'Nhập Hàng', icon: TruckIcon },
  { href: '/admin/chat', label: 'Trò Chuyện', icon: ChatBubbleLeftRightIcon },
];

export const MANAGER_ROUTES = [
  {
    href: '/manager/product-management',
    label: 'Sản Phẩm',
    icon: InboxStackIcon,
  },
  {
    href: '/manager/product-item-management',
    label: 'Mặt Hàng Sản Phẩm',
    icon: Square3Stack3DIcon,
  },
  {
    href: '/manager/size-management',
    label: 'Kích Thước',
    icon: ViewfinderCircleIcon,
  },
  {
    href: '/manager/size-type-management',
    label: 'Loại Kích Thước',
    icon: ArrowsPointingOutIcon,
  },
  {
    href: '/manager/store-management',
    label: 'Cửa Hàng',
    icon: BuildingStorefrontIcon,
  },
  { href: '/manager/color-management', label: 'Màu', icon: SparklesIcon },
  {
    href: '/manager/brand-management',
    label: 'Thương Hiệu',
    icon: RectangleGroupIcon,
  },
  {
    href: '/manager/category-management',
    label: 'Danh Mục',
    icon: RectangleStackIcon,
  },
  {
    href: '/manager/order-management',
    label: 'Đơn Hàng',
    icon: ArchiveBoxIcon,
  },
  {
    href: '/manager/supplier-management',
    label: 'Nhà Cung Cấp',
    icon: UserGroupIcon,
  },
  { href: '/manager/import-management', label: 'Nhập Hàng', icon: TruckIcon },
  { href: '/manager/chat', label: 'Trò Chuyện', icon: ChatBubbleLeftRightIcon },
];
